-- Brand analytics: reconcile the actual rollup days touched by metric refreshes.
--
-- Run after 20260726_brand_analytics_review_fixes.sql.
--
-- Why this exists:
-- A submission created six months ago still belongs to its six-month-old
-- rollup bucket when its metrics are refreshed today. Reconciliation based
-- only on today's date cannot detect drift in that old bucket.
--
-- This migration:
--   1. records the OLD and NEW UTC day keys of analytics-changing writes;
--   2. seeds every historical source/rollup day once, covering any initial
--      creator-backfill race;
--   3. provides a bounded scheduler function that repairs queued days.

BEGIN;

DO $$
BEGIN
  IF to_regprocedure(
    'public.admin_analytics_reconcile_rollups(date,date,boolean)'
  ) IS NULL THEN
    RAISE EXCEPTION
      'Prerequisite missing: apply 20260726_brand_analytics_review_fixes.sql first';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.admin_analytics_rollup_dirty_days (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_key date NOT NULL,
  marked_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS idx_admin_analytics_rollup_dirty_days_marked
  ON public.admin_analytics_rollup_dirty_days (marked_at, day_key);

CREATE INDEX IF NOT EXISTS idx_admin_analytics_rollup_dirty_days_day
  ON public.admin_analytics_rollup_dirty_days (day_key);

COMMENT ON TABLE public.admin_analytics_rollup_dirty_days IS
  'UTC source-created days that must be checked by analytics rollup reconciliation.';

CREATE OR REPLACE FUNCTION public.admin_analytics_mark_rollup_dirty_day(
  p_day_key date
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_day_key IS NULL THEN
    RETURN;
  END IF;

  INSERT INTO public.admin_analytics_rollup_dirty_days (
    day_key,
    marked_at
  )
  VALUES (
    p_day_key,
    clock_timestamp()
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_analytics_mark_submission_rollup_dirty()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Match the rollup trigger's no-op detection so bookkeeping-only refreshes
  -- do not create unnecessary reconciliation work.
  IF TG_OP = 'UPDATE'
    AND OLD.contest_id IS NOT DISTINCT FROM NEW.contest_id
    AND OLD.creator_id IS NOT DISTINCT FROM NEW.creator_id
    AND OLD.created_at IS NOT DISTINCT FROM NEW.created_at
    AND OLD.status IS NOT DISTINCT FROM NEW.status
    AND OLD.platform IS NOT DISTINCT FROM NEW.platform
    AND OLD.views IS NOT DISTINCT FROM NEW.views
    AND OLD.other_stats IS NOT DISTINCT FROM NEW.other_stats
    AND OLD.earnings IS NOT DISTINCT FROM NEW.earnings
    AND OLD.bonus_amount IS NOT DISTINCT FROM NEW.bonus_amount THEN
    RETURN NEW;
  END IF;

  -- Acquire the same shared lock before touching the dirty-day table. This
  -- prevents a lock-order deadlock with the reconciliation function, which
  -- takes the matching exclusive lock before reading/deleting queued days.
  PERFORM pg_advisory_xact_lock_shared(71026, 1);

  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    PERFORM public.admin_analytics_mark_rollup_dirty_day(
      (OLD.created_at AT TIME ZONE 'UTC')::date
    );
  END IF;

  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    PERFORM public.admin_analytics_mark_rollup_dirty_day(
      (NEW.created_at AT TIME ZONE 'UTC')::date
    );
  END IF;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_admin_analytics_rollup_dirty_submissions
  ON public.submissions;
CREATE TRIGGER trg_admin_analytics_rollup_dirty_submissions
  AFTER INSERT OR DELETE OR UPDATE OF
    contest_id,
    creator_id,
    created_at,
    status,
    platform,
    views,
    other_stats,
    earnings,
    bonus_amount
  ON public.submissions
  FOR EACH ROW
  EXECUTE FUNCTION public.admin_analytics_mark_submission_rollup_dirty();

DROP TRIGGER IF EXISTS trg_admin_analytics_rollup_dirty_pc
  ON public.post_campaign_submission_metrics;
CREATE TRIGGER trg_admin_analytics_rollup_dirty_pc
  AFTER INSERT OR DELETE OR UPDATE OF
    contest_id,
    creator_id,
    created_at,
    status,
    platform,
    views,
    other_stats,
    earnings,
    bonus_amount
  ON public.post_campaign_submission_metrics
  FOR EACH ROW
  EXECUTE FUNCTION public.admin_analytics_mark_submission_rollup_dirty();

-- Seed every historical source day so one complete pass also verifies the
-- initial creator backfill. Include existing rollup-only days so stale orphan
-- buckets are removed as well.
INSERT INTO public.admin_analytics_rollup_dirty_days (
  day_key,
  marked_at
)
SELECT
  days.day_key,
  clock_timestamp()
FROM (
  SELECT DISTINCT
    (s.created_at AT TIME ZONE 'UTC')::date AS day_key
  FROM public.submissions s
  WHERE s.created_at IS NOT NULL

  UNION

  SELECT DISTINCT
    (pcs.created_at AT TIME ZONE 'UTC')::date AS day_key
  FROM public.post_campaign_submission_metrics pcs
  WHERE pcs.created_at IS NOT NULL

  UNION

  SELECT DISTINCT r.day_key
  FROM public.admin_analytics_submission_daily_rollup r

  UNION

  SELECT DISTINCT r.day_key
  FROM public.admin_analytics_pc_daily_rollup r

  UNION

  SELECT DISTINCT r.day_key
  FROM public.admin_analytics_creator_daily_rollup r

  UNION

  SELECT DISTINCT r.day_key
  FROM public.admin_analytics_pc_creator_daily_rollup r
) AS days
WHERE days.day_key IS NOT NULL;

CREATE OR REPLACE FUNCTION public.admin_analytics_reconcile_dirty_rollups(
  p_max_days integer DEFAULT 7,
  p_repair boolean DEFAULT true
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_max_days integer := GREATEST(1, LEAST(COALESCE(p_max_days, 7), 31));
  v_repair boolean := COALESCE(p_repair, true);
  v_day date;
  v_result jsonb;
  v_results jsonb := '[]'::jsonb;
  v_processed integer := 0;
  v_remaining bigint := 0;
  v_submission_drift bigint := 0;
  v_pc_drift bigint := 0;
  v_creator_drift bigint := 0;
  v_pc_creator_drift bigint := 0;
BEGIN
  IF current_setting('transaction_isolation') <> 'read committed' THEN
    RAISE EXCEPTION
      'Dirty rollup reconciliation must run in a READ COMMITTED transaction';
  END IF;

  -- Stabilize both source writes and the queue for the complete batch.
  PERFORM pg_advisory_xact_lock(71026, 1);

  FOR v_day IN
    SELECT d.day_key
    FROM public.admin_analytics_rollup_dirty_days d
    GROUP BY d.day_key
    ORDER BY MIN(d.marked_at), d.day_key
    LIMIT v_max_days
  LOOP
    v_result := public.admin_analytics_reconcile_rollups(
      v_day,
      v_day,
      v_repair
    );

    v_processed := v_processed + 1;
    v_submission_drift := v_submission_drift
      + COALESCE((v_result #>> '{driftBuckets,submissions}')::bigint, 0);
    v_pc_drift := v_pc_drift
      + COALESCE((v_result #>> '{driftBuckets,pcSubmissions}')::bigint, 0);
    v_creator_drift := v_creator_drift
      + COALESCE((v_result #>> '{driftBuckets,creators}')::bigint, 0);
    v_pc_creator_drift := v_pc_creator_drift
      + COALESCE((v_result #>> '{driftBuckets,pcCreators}')::bigint, 0);
    v_results := v_results || jsonb_build_array(v_result);

    IF v_repair THEN
      DELETE FROM public.admin_analytics_rollup_dirty_days d
      WHERE d.day_key = v_day;
    END IF;
  END LOOP;

  SELECT COUNT(DISTINCT d.day_key)::bigint
  INTO v_remaining
  FROM public.admin_analytics_rollup_dirty_days d;

  RETURN jsonb_build_object(
    'processedDays', v_processed,
    'remainingDays', v_remaining,
    'repaired', v_repair,
    'driftBuckets', jsonb_build_object(
      'submissions', v_submission_drift,
      'pcSubmissions', v_pc_drift,
      'creators', v_creator_drift,
      'pcCreators', v_pc_creator_drift
    ),
    'days', v_results
  );
END;
$$;

COMMENT ON FUNCTION public.admin_analytics_reconcile_dirty_rollups(
  integer, boolean
) IS
  'Checks queued UTC source days, including historical submissions refreshed today. Process at most 31 days per low-traffic call.';

REVOKE ALL ON TABLE public.admin_analytics_rollup_dirty_days
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_analytics_mark_rollup_dirty_day(date)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_analytics_mark_submission_rollup_dirty()
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_analytics_reconcile_dirty_rollups(
  integer, boolean
) FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE public.admin_analytics_rollup_dirty_days
  TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_analytics_reconcile_dirty_rollups(
  integer, boolean
) TO service_role;

COMMIT;
