import { createClient } from "@/utils/supabase/server";
import { redirect } from "next/navigation";
import { verifyAdminAccess } from "@/utils/admin-auth";
import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from "@/components/ui/card";
import { Trophy, Video, User, Building, DollarSign } from "lucide-react";
import { formatCurrencyFromCents } from "@/lib/currency-utils";

export default async function AdminDashboardPage() {
    // Verify admin access
    const { isAdmin, error } = await verifyAdminAccess();

    if (!isAdmin) {
        console.log('Non-admin user attempted to access admin dashboard:', error);
        redirect("/dashboard");
    }

    const supabase = await createClient();

    try {
        // Fetch platform-wide statistics for admin
        const [
            { data: allContests },
            { data: allSubmissions },
            { data: allUsers },
            { data: totalBudget }
        ] = await Promise.all([
            supabase.from("contests").select("id, contest_type, contest_based_details, created_at"),
            supabase.from("submissions").select("id, views, status"),
            supabase.from("users").select("id, user_type, created_at"),
            supabase.from("contests").select("contest_based_details")
        ]);

        // Calculate platform statistics
        const totalContests = allContests?.length || 0;
        const totalViews = allSubmissions?.reduce((sum, sub) => sum + (sub.views || 0), 0) || 0;
        const totalCreators = allUsers?.filter(user => user.user_type === 'creator').length || 0;
        const totalBrands = allUsers?.filter(user => user.user_type === 'advertiser').length || 0;

        // Calculate total money spent by brands
        const totalMoneySpent = totalBudget?.reduce((sum, contest) => {
            if (contest.contest_based_details?.leaderboard_contest?.total_prize) {
                return sum + contest.contest_based_details.leaderboard_contest.total_prize;
            } else if (contest.contest_based_details?.cpm_contest?.total_budget) {
                return sum + contest.contest_based_details.cpm_contest.total_budget;
            }
            return sum;
        }, 0) || 0;

        // Get recent activity
        const recentContests = allContests?.slice(0, 5)?.sort((a, b) =>
            new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
        ) || [];

        return (
            <div className="space-y-8">
                <div className="flex items-center justify-between">
                    <div>
                        <h2 className="text-3xl font-bold tracking-tight">Admin Dashboard</h2>
                        <p className="text-muted-foreground">Platform-wide statistics and management</p>
                    </div>
                </div>

                {/* Platform Statistics */}
                <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">
                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">
                                Total Contests
                            </CardTitle>
                            <Trophy className="h-4 w-4 text-muted-foreground" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{totalContests}</div>
                            <p className="text-xs text-muted-foreground">
                                All contests on platform
                            </p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">
                                Total Views
                            </CardTitle>
                            <Video className="h-4 w-4 text-muted-foreground" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">
                                {totalViews.toLocaleString()}
                            </div>
                            <p className="text-xs text-muted-foreground">
                                Views generated by all submissions
                            </p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">
                                Total Creators
                            </CardTitle>
                            <User className="h-4 w-4 text-muted-foreground" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{totalCreators}</div>
                            <p className="text-xs text-muted-foreground">
                                Registered creators
                            </p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">
                                Total Brands
                            </CardTitle>
                            <Building className="h-4 w-4 text-muted-foreground" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">{totalBrands}</div>
                            <p className="text-xs text-muted-foreground">
                                Registered brands
                            </p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle className="text-sm font-medium">
                                Money Spent
                            </CardTitle>
                            <DollarSign className="h-4 w-4 text-muted-foreground" />
                        </CardHeader>
                        <CardContent>
                            <div className="text-2xl font-bold">
                                {formatCurrencyFromCents(totalMoneySpent)}
                            </div>
                            <p className="text-xs text-muted-foreground">
                                Total spent by all brands
                            </p>
                        </CardContent>
                    </Card>
                </div>

                {/* Recent Activity */}
                <div className="grid gap-4 md:grid-cols-2">
                    <Card>
                        <CardHeader>
                            <CardTitle>Recent Contest Activity</CardTitle>
                            <CardDescription>
                                Latest contests created on the platform
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            {recentContests.length > 0 ? (
                                <div className="space-y-4">
                                    {recentContests.map((contest) => (
                                        <div key={contest.id} className="flex items-center space-x-4">
                                            <Trophy className="h-4 w-4 text-muted-foreground" />
                                            <div className="flex-1 space-y-1">
                                                <p className="text-sm font-medium leading-none">
                                                    Contest ID: {contest.id.substring(0, 8)}...
                                                </p>
                                                <p className="text-xs text-muted-foreground">
                                                    Type: {contest.contest_type || 'Unknown'} • {new Date(contest.created_at).toLocaleDateString()}
                                                </p>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <p className="text-sm text-muted-foreground">No recent contests</p>
                            )}
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader>
                            <CardTitle>Platform Overview</CardTitle>
                            <CardDescription>
                                Quick insights about platform usage
                            </CardDescription>
                        </CardHeader>
                        <CardContent>
                            <div className="space-y-4">
                                <div className="flex items-center justify-between">
                                    <span className="text-sm font-medium">User Distribution</span>
                                </div>
                                <div className="space-y-2">
                                    <div className="flex items-center justify-between text-sm">
                                        <span>Creators</span>
                                        <span className="font-medium">{totalCreators}</span>
                                    </div>
                                    <div className="flex items-center justify-between text-sm">
                                        <span>Brands</span>
                                        <span className="font-medium">{totalBrands}</span>
                                    </div>
                                    <div className="flex items-center justify-between text-sm">
                                        <span>Total Views</span>
                                        <span className="font-medium">{totalViews.toLocaleString()}</span>
                                    </div>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        );

    } catch (error) {
        console.error('Error fetching admin dashboard data:', error);
        return (
            <div className="flex items-center justify-center h-64">
                <p className="text-muted-foreground">Error loading admin dashboard</p>
            </div>
        );
    }
} 