import type { ExportReportBranding } from "@/lib/report-export-branding";
import { GOC_PLATFORM_NAME, GOC_TAGLINE } from "@/lib/report-export-branding";
import type { ReportCoverMetrics } from "@/lib/report-export-metrics";
import { formatLocalDateTime } from "@/lib/utils";

export type CampaignCoverKpi = {
  label: string;
  value: string;
  subtext: string;
};

export type CampaignCoverMarketing = {
  targetCpm?: string;
  effectiveCpm?: string;
  cpmEfficiency?: string;
};

export type CoverHeroMetric = {
  value: string;
  label: string;
  subline: string;
};

export type CoverTrustMeta = {
  reportId: string;
  generatedTimestamp: string;
  dataScopeLabel: string;
  engineLabel: string;
};

/** Dynamic data for the premium React-PDF cover page */
export type CampaignCoverReportData = {
  brandName: string;
  campaignName: string;
  dataScopeLabel: string;
  exportDate: string;
  filters: string;
  heroMetric: CoverHeroMetric;
  insightSentence: string;
  trust: CoverTrustMeta;
  kpis: CampaignCoverKpi[];
  marketing?: CampaignCoverMarketing;
};

/** Enterprise abbreviated number formatting for cover metrics */
export function formatCoverMetricValue(value: number): string {
  if (value >= 1_000_000) {
    const millions = Math.round((value / 1_000_000) * 10) / 10;
    const formatted = Number.isInteger(millions)
      ? String(millions)
      : millions.toFixed(1);
    return `${formatted}M`;
  }
  if (value >= 100_000) {
    return `${Math.round(value / 1_000)}K`;
  }
  if (value >= 1_000) {
    const thousands = Math.floor((value / 1_000) * 10) / 10;
    const formatted = Number.isInteger(thousands)
      ? String(thousands)
      : thousands.toFixed(1);
    return `${formatted}K`;
  }
  return value.toLocaleString();
}

export function buildCoverHeroMetric(metrics: ReportCoverMetrics): CoverHeroMetric {
  const submissions = Number(metrics.totalSubmissions).toLocaleString();
  const subline = metrics.effectiveCpmFormatted
    ? `Generated from ${submissions} creator submissions\nwith an effective CPM of ${metrics.effectiveCpmFormatted}`
    : `Generated from ${submissions} creator submissions`;

  return {
    value: formatCoverMetricValue(metrics.totalViews),
    label: "Campaign Views",
    subline,
  };
}

export function buildCoverInsightSentence(
  metrics: ReportCoverMetrics,
  viewsFormatted: string,
): string {
  const subs = Number(metrics.totalSubmissions).toLocaleString();

  if (metrics.effectiveCpmFormatted) {
    return `The campaign generated ${viewsFormatted} views from ${subs} creator submissions while achieving an effective CPM of ${metrics.effectiveCpmFormatted}.`;
  }

  return `The campaign generated ${viewsFormatted} views from ${subs} creator submissions.`;
}

export function buildCoverEngineLabel(): string {
  const tagline = GOC_TAGLINE.replace(/\.$/, "");
  return `Generated by ${GOC_PLATFORM_NAME} - ${tagline}`;
}

export function buildCampaignCoverReportData(
  branding: ExportReportBranding,
  metrics: ReportCoverMetrics,
): CampaignCoverReportData {
  const dateRange = formatCampaignDateRange(branding);
  const filters =
    branding.filtersApplied || branding.dataScopeLabel || "All Submissions Data";

  const spendSubtext = metrics.spendLabel.toLowerCase().includes("paid")
    ? "Total amount paid"
    : "Total prize pool";

  const heroMetric = buildCoverHeroMetric(metrics);
  const insightSentence = buildCoverInsightSentence(
    metrics,
    heroMetric.value,
  );

  const kpis: CampaignCoverKpi[] = [
    {
      label: "Total Submissions",
      value: metrics.totalSubmissionsLabel,
      subtext: "Total entries received",
    },
    {
      label: "Total Views",
      value: formatCoverMetricValue(metrics.totalViews),
      subtext: "Across all content",
    },
    {
      label: metrics.spendLabel,
      value: metrics.spendFormatted,
      subtext: spendSubtext,
    },
    {
      label: "Contest Duration",
      value: metrics.durationLabel.replace(/\bdays\b/i, "Days"),
      subtext: dateRange ?? "",
    },
  ];

  const marketing: CampaignCoverMarketing | undefined =
    metrics.showMarketingBlock
      ? {
          targetCpm: metrics.targetCpmFormatted ?? undefined,
          effectiveCpm: metrics.effectiveCpmFormatted ?? undefined,
          cpmEfficiency: metrics.cpmEfficiency ?? undefined,
        }
      : undefined;

  return {
    brandName: branding.brandCompanyName,
    campaignName: branding.contestTitle,
    dataScopeLabel: branding.dataScopeLabel,
    exportDate: branding.exportDateLabel,
    filters,
    heroMetric,
    insightSentence,
    trust: {
      reportId: branding.reportId,
      generatedTimestamp: branding.exportedAt,
      dataScopeLabel: branding.dataScopeLabel,
      engineLabel: buildCoverEngineLabel(),
    },
    kpis,
    marketing,
  };
}

function formatCampaignDateRange(branding: ExportReportBranding): string | null {
  if (branding.contestStart && branding.contestEnd) {
    const start = formatLocalDateTime(branding.contestStart, {
      day: "2-digit",
      month: "short",
    });
    const end = formatLocalDateTime(branding.contestEnd, {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
    return `${start} – ${end}`;
  }
  if (branding.durationDays != null) {
    return `${branding.durationDays} days`;
  }
  return null;
}
