import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  buildCampaignCoverReportData,
  buildCoverEngineLabel,
  buildCoverHeroMetric,
  buildCoverInsightSentence,
  formatCoverMetricValue,
} from "@/lib/report-export-pdf-cover-data";
import {
  wrapPdfTitleLines,
} from "@/lib/report-export-pdf-premium-shared";
import type { ExportReportBranding } from "@/lib/report-export-branding";
import type { ReportCoverMetrics } from "@/lib/report-export-metrics";
import {
  buildReportIdFromInstant,
  formatReportGeneratedTimestampIST,
} from "@/lib/report-export-timestamp";

function baseMetrics(
  partial: Partial<ReportCoverMetrics> = {},
): ReportCoverMetrics {
  return {
    totalSubmissions: 1065,
    totalSubmissionsLabel: "1065",
    totalViews: 21_347_281,
    totalViewsFormatted: "21,347,281",
    totalReach: 0,
    totalEngagements: 0,
    spendCents: 35742,
    spendLabel: "Amount Paid",
    spendFormatted: "$357.42",
    durationLabel: "23 days",
    targetCpmUsd: 0.2,
    targetCpmFormatted: "$0.200",
    effectiveCpmUsd: 0.017,
    effectiveCpmFormatted: "$0.017",
    cpmEfficiency: "11.8×",
    insightSentence:
      "The campaign delivered views at 91% lower cost than the target CPM of $0.200.",
    showMarketingBlock: true,
    ...partial,
  };
}

function baseBranding(
  partial: Partial<ExportReportBranding> = {},
): ExportReportBranding {
  return {
    brandCompanyName: "Beer Biceps",
    platformName: "Game of Creators",
    contestTitle: "Ranveer: BTS, Vlogs & Documentaries (Special Campaign)",
    reportTitle: "Campaign Performance Report",
    reportDescription: "All data",
    exportedAt: "11 Jun 2026, 10:21:01 pm IST",
    exportDateLabel: "11 Jun 2026",
    reportId: "GOC-20260611102101",
    dataScopeLabel: "Verified + Paid Submissions Data",
    reportType: "full",
    contestId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    contestLifecycleStatus: "ended",
    postContestStatus: "payouts_processed",
    ...partial,
  };
}

describe("report-export-pdf-cover-data", () => {
  it("formats numbers using enterprise abbreviations", () => {
    assert.equal(formatCoverMetricValue(1_250), "1.2K");
    assert.equal(formatCoverMetricValue(125_000), "125K");
    assert.equal(formatCoverMetricValue(1_250_000), "1.3M");
    assert.equal(formatCoverMetricValue(21_347_281), "21.3M");
  });

  it("always uses Campaign Views for the hero metric", () => {
    const hero = buildCoverHeroMetric(baseMetrics());
    assert.equal(hero.value, "21.3M");
    assert.equal(hero.label, "Campaign Views");
    assert.match(hero.subline, /Generated from 1,065 creator submissions/);
    assert.match(hero.subline, /effective CPM of \$0\.017/);
  });

  it("builds the insight sentence with views and CPM", () => {
    const hero = buildCoverHeroMetric(baseMetrics());
    const insight = buildCoverInsightSentence(baseMetrics(), hero.value);
    assert.match(
      insight,
      /The campaign generated 21\.3M views from 1,065 creator submissions/,
    );
    assert.match(insight, /effective CPM of \$0\.017/);
  });

  it("builds cover data with timestamp report id and dynamic scope label", () => {
    const cover = buildCampaignCoverReportData(baseBranding(), baseMetrics());
    assert.equal(cover.trust.reportId, "GOC-20260611102101");
    assert.equal(cover.dataScopeLabel, "Verified + Paid Submissions Data");
    assert.equal(cover.trust.dataScopeLabel, "Verified + Paid Submissions Data");
    assert.match(cover.trust.engineLabel, /Generated by Game of Creators/);
    assert.match(
      cover.trust.engineLabel,
      /India\u2019s First & Largest Purely Performance-Driven Viral Marketing Engine/,
    );
  });

  it("wraps long campaign titles without orphan prefix lines", () => {
    const wrapped = wrapPdfTitleLines(
      "Ranveer: BTS, Vlogs & Documentaries (Special Campaign)",
    );
    assert.match(wrapped, /^Ranveer:\u00A0BTS, Vlogs & Documentaries\n\(/);
    assert.doesNotMatch(wrapped, /^\(/);
  });

  it("builds engine label with platform name and tagline", () => {
    const label = buildCoverEngineLabel();
    assert.match(label, /Generated by Game of Creators - /);
    assert.doesNotMatch(label, /Intelligence Engine/);
  });
});

describe("report-export-timestamp", () => {
  it("builds report ids from download instant in IST", () => {
    const instant = new Date("2026-06-11T16:51:01.000Z");
    assert.equal(buildReportIdFromInstant(instant), "GOC-20260611102101");
  });

  it("formats generated timestamps with IST suffix", () => {
    const instant = new Date("2026-06-11T16:51:01.000Z");
    const formatted = formatReportGeneratedTimestampIST(instant);
    assert.match(formatted, /IST$/);
    assert.match(formatted, /2026/);
  });
});
